/**
 * Web (Next.js) Service Starter
 *
 * Provides `startWeb()` for the SERVICE_MODE-driven combined process.
 *
 * In production the standalone `server.js` (generated by `next build`) is
 * forked as a child process.  When `server.js` does not exist (fresh clone,
 * local dev) the starter falls back to `next dev --turbo` so that
 * `pnpm dev:all` works out of the box without a prior build step.
 */
import { createLogger } from "@/lib/logger";
import { env } from "@/env";
import { fork, type ChildProcess } from "child_process";
import fs from "fs";
import path from "path";
import http from "http";

const log = createLogger("web");

export interface WebHandle {
  shutdown: () => Promise<void>;
}

export async function startWeb(): Promise<WebHandle> {
  const port = env.PORT;
  const hostname = env.WEB_HOST;

  const serverJs = path.resolve(process.cwd(), "server.js");

  let child: ChildProcess;

  if (fs.existsSync(serverJs)) {
    child = fork(serverJs, {
      env: {
        ...process.env,
        PORT: String(port),
        HOSTNAME: hostname,
      },
      stdio: "inherit",
    });
  } else {
    log.info("server.js not found — starting Next.js in dev mode");
    const nextBin = path.resolve(
      process.cwd(),
      "node_modules",
      "next",
      "dist",
      "bin",
      "next",
    );
    child = fork(
      nextBin,
      [
        "dev",
        // Keep the local Docker experience within a bounded compilation footprint.
        ...(env.NEXT_PUBLIC_LOCAL_DEMO === "on" ? [] : ["--turbo"]),
        "--port",
        String(port),
        "--hostname",
        hostname,
      ],
      {
        env: {
          ...process.env,
          PORT: String(port),
          HOSTNAME: hostname,
        },
        stdio: "inherit",
      },
    );
  }

  child.on("error", (err) => {
    log.error({ error: err }, "Next.js child process error");
  });

  child.on("exit", (code, signal) => {
    if (code !== 0 && code !== null) {
      log.error({ code, signal }, "Next.js child process exited unexpectedly");
    }
  });

  await waitForPort(port, hostname, 60_000);
  log.info({ port, hostname }, `Next.js server listening on port ${port}`);

  const shutdown = () =>
    new Promise<void>((resolve) => {
      if (!child.connected && child.exitCode !== null) {
        resolve();
        return;
      }
      child.once("exit", () => {
        log.info("Next.js child process stopped");
        resolve();
      });
      child.kill("SIGTERM");
      setTimeout(() => {
        child.kill("SIGKILL");
        resolve();
      }, 5000);
    });

  return { shutdown };
}

function waitForPort(
  port: number,
  host: string,
  timeoutMs: number,
): Promise<void> {
  const start = Date.now();
  return new Promise((resolve, reject) => {
    const check = () => {
      const req = http.get(
        { host, port, path: "/healthz", timeout: 2000 },
        (res) => {
          res.resume();
          resolve();
        },
      );
      req.on("error", () => {
        if (Date.now() - start > timeoutMs) {
          reject(new Error(`Next.js did not start within ${timeoutMs}ms`));
          return;
        }
        setTimeout(check, 500);
      });
      req.end();
    };
    check();
  });
}
